[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --alluredir=allure-results --clean-alluredir
markers =
    smoke: smoke tests
    regression: regression tests
    negative: negative tests
    contract: contract tests
