name: API autotests

"on":
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Java (for Allure)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Install API deps
        run: pip install -r edu_api_demo_v3_sqlite/requirements.txt

      - name: Install test deps
        run: pip install -r edu_api_test_framework/requirements.txt

      - name: Start API
        run: |
          cd edu_api_demo_v3_sqlite
          nohup uvicorn app.main:app --host 127.0.0.1 --port 8000 > api.log 2>&1 &

      - name: Wait for API
        run: |
          for i in {1..30}; do
            if curl -s http://127.0.0.1:8000/health_check; then
              echo "API ready"
              exit 0
            fi
            sleep 2
          done
          echo "API failed"
          exit 1

      - name: Run tests
        continue-on-error: true
        run: |
          cd edu_api_test_framework
          pytest --alluredir=allure-results

      - name: Generate Allure report
        run: |
          cd edu_api_test_framework
          allure generate allure-results -o allure-report --clean

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: edu_api_test_framework/allure-report

  deploy:
  needs: test
  runs-on: ubuntu-latest

  environment:
    name: github-pages
    url: https://vernefunny.github.io/api-testing-diploma/

  permissions:
    pages: write
    id-token: write

  steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4

    - name: Print Allure URL
      run: echo "Allure report: https://vernefunny.github.io/api-testing-diploma/"

	